// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1q5SMG-pToUX8J_nb3fCUUuNPteYjafg',
    appId: '1:5354461580:web:4257803df6d3953e2fdea9',
    messagingSenderId: '5354461580',
    projectId: 'smartcontainer-13e6e',
    authDomain: 'smartcontainer-13e6e.firebaseapp.com',
    databaseURL: 'https://smartcontainer-13e6e-default-rtdb.firebaseio.com',
    storageBucket: 'smartcontainer-13e6e.firebasestorage.app',
    measurementId: 'G-N0KWZWHRMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpbmQl-7EwN1axSXYPTvohvz6AJq4q83Q',
    appId: '1:5354461580:android:7a2c6d4569495df92fdea9',
    messagingSenderId: '5354461580',
    projectId: 'smartcontainer-13e6e',
    databaseURL: 'https://smartcontainer-13e6e-default-rtdb.firebaseio.com',
    storageBucket: 'smartcontainer-13e6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa0xQfLL-3OBoCRxkiDUTf17limAqWCDI',
    appId: '1:5354461580:ios:2cd6a8bdae0897262fdea9',
    messagingSenderId: '5354461580',
    projectId: 'smartcontainer-13e6e',
    databaseURL: 'https://smartcontainer-13e6e-default-rtdb.firebaseio.com',
    storageBucket: 'smartcontainer-13e6e.firebasestorage.app',
    iosBundleId: 'com.example.smartContainerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa0xQfLL-3OBoCRxkiDUTf17limAqWCDI',
    appId: '1:5354461580:ios:2cd6a8bdae0897262fdea9',
    messagingSenderId: '5354461580',
    projectId: 'smartcontainer-13e6e',
    databaseURL: 'https://smartcontainer-13e6e-default-rtdb.firebaseio.com',
    storageBucket: 'smartcontainer-13e6e.firebasestorage.app',
    iosBundleId: 'com.example.smartContainerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1q5SMG-pToUX8J_nb3fCUUuNPteYjafg',
    appId: '1:5354461580:web:2b5d2f23331f7ae02fdea9',
    messagingSenderId: '5354461580',
    projectId: 'smartcontainer-13e6e',
    authDomain: 'smartcontainer-13e6e.firebaseapp.com',
    databaseURL: 'https://smartcontainer-13e6e-default-rtdb.firebaseio.com',
    storageBucket: 'smartcontainer-13e6e.firebasestorage.app',
    measurementId: 'G-3CPQWQ1J7X',
  );
}
